### PR TITLE
Fix: object_default/schema

### PR DESCRIPTION
**Pull request by younesdessia**
* **What kind of changes does this PR introduce?** 
- [X] Bug fix
- [ ] new features
- [ ] performance 
- [ ] docs update

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
- [ ] Yes:
- [X] No

* **Other information**:

### CODE REVIEW

**Review by GhislainJ — CHANGES_REQUESTED** [review]
We need more context about this, as None as default value should directly happen with objects. We should normally have an Optional schema

**Comment by younesdessia** [comment]
Another fix, replace None value of `default_value` with `UNDEFINED` in `SchemaAttribute` class:  

image

**Review by GhislainJ — APPROVED** [review]

**Comment by GhislainJ** [comment]
Approved but adding tests are needed to merge

**Review by GhislainJ — CHANGES_REQUESTED** [review]
Tests using you simplified repro case should be added

**Comment by younesdessia** [comment]
Done !

**Review by GhislainJ — APPROVED** [review]

**Pull request merged**
